Add `intermediary_mappings` field to `quilt.mod.json`
QuiltMC/rfcs pull request #52
Opened 2022-04-02 03:01 UTC by TibiNonEst

Per https://github.com/QuiltMC/quilt-loader/issues/59.

Adds an optional string field to `quilt.mod.json` in the `quilt_loader` section named `intermediate_mappings`. This string will be used to determine which mappings a mod uses once hashed support is added to QL. The two values it will accept are `"hashed"` and `"intermediary"`.

2022-04-02 16:19 UTC, TheGlitch76 requested changes

2022-04-02 16:19 UTC, TheGlitch76 commented on specification/0002-quilt.mod.json.md
> +| String | False    |
include the default value here as in other parts of this document

2022-04-02 20:27 UTC, TheGlitch76 approved these changes
This will be merged along with the PR to Loader

2022-04-02 20:40 UTC, zml2008 commented
How about using maven coordinates for this, to have a global identifier for mappings, such as `net.fabricmc:intermediary` and `org.quiltmc:hashed`. This would allow for other namespaces to be contributed, say by loader plugins -- if someone wanted to do say a custom intermediary for legacy versions, or use srg.

2022-04-04 15:53 UTC, TibiNonEst commented
My initial idea was that loader plugins could register additional intermediate mapping identifiers such as `"legacy"` or whatever such an identifier may be, although I think using maven coordinates may be better for guaranteeing uniqueness and may make loader plugins easier to create down the line.

2022-04-05 19:48 UTC, chexo3 commented
> I agree, the maven coordinates would be better for a general approach.
> 
> Should we bother providing aliases matching what was initially proposed here (reserved just for hashed and fabric intermediary), or always use the maven coordinates?

If we were already using this code in production it would make sense, but in this case we can do it without having to worry about old mods, so aliases might be kind of pointless. I think in this case being specific makes sense.

2022-04-10 18:51 UTC, AlexIIL approved these changes

2022-04-10 21:01 UTC, TheGlitch76 commented
Can an admin merge this, please?

2022-04-10 21:01 UTC, wafflecoffee commented on specification/0002-quilt.mod.json.md
> +The intermediate mappings used for this mod. The intermediate mappings string must be a valid maven coordinate and match the `^[a-zA-Z0-9-_.]+:[a-zA-Z0-9-_.]+$` regular expresson. This field currentl
```suggestion
The intermediate mappings used for this mod. The intermediate mappings string must be a valid maven coordinate and match the `^[a-zA-Z0-9-_.]+:[a-zA-Z0-9-_.]+$` regular expression. This field currently only officially supports `org.quiltmc:hashed` and `net.fabricmc:intermediary`.
```

2022-04-10 21:04 UTC, OroArmor commented
I'll merge when the last comment is resolved.

2022-04-10 21:04 UTC, wafflecoffee commented
@OroArmor You can just commit it yourself, no? I didn't mean for that to be a blocking comment, just didn't want a typo

2022-04-10 21:05 UTC, OroArmor commented
You're right I can.

2022-04-10 21:06 UTC, merged